package pipestack:customer@0.1.0;

interface customer {
    use wrpc:rpc/error@0.1.0.{error};
    run: func(input: string) -> result<string, error>;
}

world component {
    import wasi:config/runtime@0.2.0-draft;

    export customer;
}
