version: "0.5"
is_strict: true
log_location: /tmp/pc.global.log
processes:
  dev_services_infisical_secrets_provider:
      namespace: dev
      working_dir: crates/services/infisical_secrets_provider
      command: |
        cargo watch -w . -x "run"
      environment:
        - "RUST_LOG=debug"
      is_tty: true
  dev_services_pipeline_manager:
      namespace: dev
      working_dir: crates/services/pipeline_manager
      command: |
        cargo watch -w . -x "run"
      environment:
        - "RUST_LOG=debug"
      is_tty: true
      readiness_probe:
        http_get:
          host: localhost
          scheme: http
          path: "/health"
          port: 3000
          initial_delay_seconds: 10
  dev_deploy_default_providers:
    namespace: dev
    command: |
        wash app delete default-providers
        curl -X POST http://localhost:3000/deploy-providers -H "Content-Type: application/json" -d '{ "workspaceSlug": "default" }'
    is_tty: true
    depends_on:
      dev_services_pipeline_manager:
        condition: process_healthy
  dev_wash_logs:
    namespace: dev
    command: |
      just wash-logs
    is_tty: true
  dev_wash_ui:
    namespace: dev
    command: |
      wash ui
    is_tty: true
    readiness_probe:
      http_get:
        host: localhost
        scheme: http
        path: "/"
        port: 3030
