version: "0.5"
is_strict: true
log_location: /tmp/pc.global.log
processes:
  dev_services_component_composer:
      namespace: dev
      command: |
        cargo watch -x "run --bin component-composer"
      environment:
        - "RUST_LOG=debug"
      is_tty: true
  dev_services_pipeline_manager:
      namespace: dev
      command: |
        cargo watch -w crates/services/pipeline-manager -x "run --bin pipeline-manager"
      environment:
        - "RUST_LOG=debug"
      is_tty: true
  dev_wash_logs:
    namespace: dev
    command: |
      just wash-logs
    is_tty: true
  dev_wash_ui:
    namespace: dev
    command: |
      wash ui
    is_tty: true
    readiness_probe:
      http_get:
        host: localhost
        scheme: http
        path: "/"
        port: 3030
