[package]
name = "custom-component-links-only-multiple-versions"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:custom-component"

[package.metadata.component.dependencies]
