name = "customer"
language = "rust"
type = "component"
version = "0.0.1"

[component]
wasm_target = "wasm32-wasip2"

[registry.pull]
sources = [
    { target = "wrpc:rpc", source = "https://github.com/wrpc/rpc/archive/v0.1.0.tar.gz" },
]