[package]
name = "out-http-webhook"
edition = "2024"
version = "0.1.4"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json.workspace = true
shared = { path = "../../shared" , version = "0.1.3" }
wasmcloud-component.workspace = true
wit-bindgen.workspace = true
