name = "in_internal"
language = "rust"
type = "component"

[component]
wasm_target = "wasm32-wasip2"

[registry.pull]
sources = [
    { target = "pipestack:customer", source = "file://../customer/wit" },
    { target = "pipestack:out", source = "file://../out/wit" },
    { target = "wrpc:rpc", source = "https://github.com/wrpc/rpc/archive/v0.1.0.tar.gz" },
]