[package]
name = "in-http"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmbus-rpc.workspace = true
wasmcloud-component.workspace = true
wasmcloud-interface-messaging.workspace = true
wit-bindgen.workspace = true