[package]
name = "in-http"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
shared = { path = "../../shared" }
wasmcloud-component.workspace = true
wit-bindgen.workspace = true