apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: in-http
  annotations:
    version: v0.0.1
spec:
  components:
    - name: in-http-component
      type: component
      properties:
        image: file://./build/in_http_s.wasm
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: nats-msg
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]  

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
        ## To configure OTEL integration for this provider specifically, uncomment the lines below
        # config:
        #   - name: otel
        #     properties:
        #       otel_exporter_otlp_endpoint: "http://all-in-one:4318"
        #       otel_exporter_otlp_traces_endpoint: "http://traces-backend/v1/traces"
        #       otel_exporter_otlp_metrics_endpoint: "http://metrics-backend/v1/metrics"
        #       otel_exporter_otlp_logs_endpoint: "http://logs-backend/v1/logs"
      traits:
        # Establish a unidirectional link from this http server provider (the "source")
        # to the `http-component` component (the "target") so the component can handle incoming HTTP requests,
        #
        # The source (this provider) is configured such that the HTTP server listens on 0.0.0.0:8000
        - type: link
          properties:
            target:
              name: in-http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8000

    # Add a capability provider that implements `wasmcloud:messaging` using NATS
    - name: nats-msg
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.27.0
        ## To configure OTEL integration for this provider specifically, uncomment the lines below
        # config:
        #   - name: otel
        #     properties:
        #       otel_exporter_otlp_endpoint: "http://all-in-one:4318"
        #       otel_exporter_otlp_traces_endpoint: "http://traces-backend/v1/traces"
        #       otel_exporter_otlp_metrics_endpoint: "http://metrics-backend/v1/metrics"
        #       otel_exporter_otlp_logs_endpoint: "http://logs-backend/v1/logs"
      # traits:
      #   - type: link
      #     properties:
      #       target:
      #         name: in-http-component
      #       namespace: wasmcloud
      #       package: messaging
      #       interfaces: [handler]
      #       source:
      #         config:
      #           - name: nats-subscription
      #             properties:
      #               subscriptions: nats.atomic.delta