name = "in-http"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "component"
wasm_target = "wasm32-wasip2"

[registry.pull]
sources = [
    { target = "pipestack:out", source = "file://../out/wit" },
]