apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-pipeline
  annotations:
    description: A test pipeline with a hard-coded wadm file and no custom code
    version: v0.0.1
spec:
  components:
    - name: test-pipeline-01-hard-coded-wadm-no-custom-code-component-in-http
      type: component
      properties:
        image: file://../../../platform/main/crates/nodes/in-http/build/in_http_s.wasm
        # image: localhost:5000/pipestack/in-http:0.0.1
        config:
          - name: custom-config
            properties:
              topic-next-step: step-2-in
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: test-pipeline-messaging-nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]  

    - name: test-pipeline-01-hard-coded-wadm-no-custom-code-component-out-log
      type: component
      properties:
        image: file://../../../platform/main/crates/nodes/out-log/build/out_log_s.wasm
        # image: localhost:5000/pipestack/out-log:0.0.1
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    # ============
    # capabilities
    # ============
    - name: test-pipeline-httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
        config:
          - name: default-http-config
            properties:
              routing_mode: path
              address: 0.0.0.0:8000
          - name: httpserver-otel
            properties:
              otel_exporter_otlp_endpoint: "http://localhost:4318"
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            name: a
            target:
              name: test-pipeline-01-hard-coded-wadm-no-custom-code-component-in-http
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: path
                  properties:
                    path: /example-pipeline

    - name: test-pipeline-messaging-nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.27.0
        config:
          - name: messaging-nats-otel
            properties:
              otel_exporter_otlp_endpoint: "http://localhost:4318"
      traits:
        - type: spreadscaler
          properties:
            instances: 2
        - type: link
          properties:
            name: a
            target:
              name: test-pipeline-01-hard-coded-wadm-no-custom-code-component-out-log
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source:
              config:
                - name: subscription
                  properties:
                    subscriptions: step-2-in
