[package]
name = "shared"
version = "0.1.3"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
schemars.workspace = true
ts-rs.workspace = true
