on:
  push:
    branches: [main]

name: Prepare Release PR

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    if: "!contains(github.event.head_commit.message, 'chore: prepare release')" # Skip merges from releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name GitHub Actions
          git config user.email github-actions@github.com
      - uses: knope-dev/action@v2.1.0
        with:
          version: 0.21.2 # Also update config/devbox/flakes/knope/flake.nix and .github/workflows/release.yaml
      - run: knope prepare-release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}